### ISSUE TITLE
404 error on links to Bohling's website

### ISSUE THREAD

**Issue by ljwolf** [cjohnson318/geostatsmodels#13]
your references to Bohling's KU geostat course seem to be 404ing. 
Indeed, most of bohling's website appears to be broken right now; not sure if this is temporary or if this is a permanent change in the target site.

**Comment by caerus-data** [comment]
I've contacted him, and am in the process of getting WGTutorial.zip. I can share back to the main Fork.

**Comment by cjohnson318** [comment]
Reference to Bohling's page has been removed from the README, as it has not been updated since June 18, 2018.
