### ISSUE TITLE
Python 3 compatibility?

### ISSUE THREAD

**Issue by 1kastner** [cjohnson318/geostatsmodels#8]
First of all thanks for the great project! I love how everything is done step-by-step, e.g. at [0]. Now I prefer to use Python 3 - do you have any plans to update the code so that it can run with the newer Python versions as well?

[0] http://nbviewer.jupyter.org/github/cjohnson318/geostatsmodels/blob/master/notebooks/VariogramAnalysis.ipynb

**Comment by ljwolf** [comment]
Considering how you're using `urllib2`, it looks possible to swap to `requests.get` from the [`requests`](https://github.com/requests/requests) package and get compatibility in both versions.

Not sure if other incompatibilities lurk in the code, though. I've been able to import & use parts.

**Comment by 1kastner** [comment]
I'd always be pretty careful about importing and hoping since division was reworked: `5/2` is evaluated differently on Python 2 and Python 3. As we can't see which variables are floats and which are ints, this is a pretty dangerous thing. There might be some results and they might be close to the mathematically correct one, but there might be some major flaws as well.

Replacing urllib2 with requests is a nice choice but not my main concern.

**Comment by 1kastner** [comment]
Thank you for checking the floatdiv issue! When I wrote "the code" I was referring to the whole project, I was not making myself understood well, sorry for that. Btw, thanks for showing me pysal!

**Comment by 1kastner** [comment]
I just found the [commit ](https://github.com/cjohnson318/geostatsmodels/commit/ba37ddf0c1ded07df542842dbbbedcec83ed51e7) which introduced Python 3 compatibility. That makes it seem to work nicely.

**Comment by 1kastner** [comment]
@cjohnson318 alright, I guess with the commit this issue should be solved.
